In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("E:\Airline_customer_satisfaction.csv")

In [3]:
df.head()

satisfaction   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Loyal Customer   65  Personal Travel       Eco   
1    satisfied  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Loyal Customer   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   satisfaction                       129880 non-null  object 
 1   Customer Type                      129880 non-null  object 
 2   Age                                129880 non-null  int64  
 3   Type of Travel                     129880 non-null  object 
 4   Class                              129880 non-null  object 
 5   Flight Distance                    129880 non-null  int64  
 6   Seat comfort                       129880 non-null  int64  
 7   Departure/Arrival time convenient  129880 non-null  int64  
 8   Food and drink                     129880 non-null  int64  
 9   Gate location                      129880 non-null  int64  
 10  Inflight wifi service              129880 non-null  int64  
 11  Inflight entertainment             1298

In [5]:
df.isna().sum()

satisfaction                           0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Seat comfort                           0
Departure/Arrival time convenient      0
Food and drink                         0
Gate location                          0
Inflight wifi service                  0
Inflight entertainment                 0
Online support                         0
Ease of Online booking                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Online boarding                        0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
dtype: int64

In [6]:
df['satisfaction'].unique()

array(['satisfied', 'dissatisfied'], dtype=object)

In [7]:
df['satisfaction'].value_counts()

satisfaction
satisfied       71087
dissatisfied    58793
Name: count, dtype: int64

In [8]:
df['Arrival Delay in Minutes'].isnull().sum()

393

In [9]:
min_mean = df['Arrival Delay in Minutes'].mean()
min_mean

15.09112883918849

In [10]:
min_std = df['Arrival Delay in Minutes'].std()
min_std 

38.46565024014756

In [11]:
low_val = abs(min_mean - min_std)
low_val

23.37452140095907

In [12]:
high_val = min_mean+min_std
high_val

53.55677907933605

In [13]:
# filling missing values in Arrival Delay in Minutes

x_rand = np.random.randint(23,53,393)
x_rand

array([40, 23, 36, 51, 50, 37, 46, 43, 43, 34, 23, 30, 37, 49, 23, 26, 26,
       46, 48, 38, 27, 49, 52, 27, 26, 45, 46, 31, 34, 37, 28, 32, 38, 32,
       41, 47, 41, 50, 38, 27, 51, 48, 30, 33, 50, 30, 32, 27, 29, 43, 43,
       30, 36, 27, 43, 52, 47, 26, 45, 29, 51, 27, 36, 34, 36, 51, 46, 43,
       27, 49, 50, 34, 30, 33, 47, 36, 45, 29, 23, 43, 35, 42, 46, 44, 40,
       39, 27, 35, 49, 34, 34, 28, 40, 42, 47, 48, 42, 46, 29, 46, 23, 26,
       29, 47, 50, 46, 31, 35, 40, 39, 27, 26, 28, 35, 37, 34, 34, 28, 36,
       48, 32, 43, 38, 49, 51, 37, 41, 50, 34, 32, 41, 46, 36, 28, 30, 29,
       50, 36, 48, 39, 36, 29, 33, 52, 42, 30, 52, 34, 24, 51, 37, 33, 39,
       48, 31, 47, 49, 37, 28, 50, 35, 29, 24, 31, 23, 23, 29, 50, 32, 50,
       51, 31, 46, 49, 31, 31, 40, 42, 52, 28, 23, 31, 34, 38, 36, 24, 30,
       39, 24, 30, 46, 46, 48, 28, 43, 52, 23, 50, 24, 51, 47, 38, 23, 49,
       52, 31, 32, 43, 35, 46, 40, 25, 24, 42, 26, 47, 49, 25, 47, 32, 29,
       31, 30, 40, 26, 43

In [14]:
df.loc[df['Arrival Delay in Minutes'].isnull() , 'Arrival Delay in Minutes'] = x_rand

In [15]:
df['Arrival Delay in Minutes'].isnull().sum()

0

In [16]:
df.isnull().sum()

satisfaction                         0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Seat comfort                         0
Departure/Arrival time convenient    0
Food and drink                       0
Gate location                        0
Inflight wifi service                0
Inflight entertainment               0
Online support                       0
Ease of Online booking               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Cleanliness                          0
Online boarding                      0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
dtype: int64

In [17]:
# Feature engineering

# dealing with satisfaction column
df['satisfaction'] = df['satisfaction'].map({'satisfied':0,'dissatisfied':1})

In [18]:
df.head()

satisfaction   Customer Type  Age   Type of Travel     Class  \
0             0  Loyal Customer   65  Personal Travel       Eco   
1             0  Loyal Customer   47  Personal Travel  Business   
2             0  Loyal Customer   15  Personal Travel       Eco   
3             0  Loyal Customer   60  Personal Travel       Eco   
4             0  Loyal Customer   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [19]:
df['satisfaction'].unique()

array([0, 1], dtype=int64)

In [20]:
# Dealing with Customer Type
df['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [21]:
df['Customer Type']  = df['Customer Type'].map({'Loyal Customer':0,'disloyal Customer':1})

In [22]:
df.head()

satisfaction  Customer Type  Age   Type of Travel     Class  \
0             0              0   65  Personal Travel       Eco   
1             0              0   47  Personal Travel  Business   
2             0              0   15  Personal Travel       Eco   
3             0              0   60  Personal Travel       Eco   
4             0              0   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [23]:
df['Customer Type'].unique()

array([0, 1], dtype=int64)

In [24]:
# Dealing with Type of Travel column

df['Type of Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [25]:
df['Type of Travel'] = df['Type of Travel'].map({'Personal Travel':0 , 'Business travel':1})

In [26]:
df['Type of Travel'].unique()

array([0, 1], dtype=int64)

In [27]:
# Dealing with Class column
df['Class'].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [28]:
df['Class'] = df['Class'].map({'Business':0,'Eco Plus':1,'Eco':2})

In [29]:
df['Class'].unique()

array([2, 0, 1], dtype=int64)

In [30]:
df.head()

satisfaction  Customer Type  Age  Type of Travel  Class  Flight Distance  \
0             0              0   65               0      2              265   
1             0              0   47               0      0             2464   
2             0              0   15               0      2             2138   
3             0              0   60               0      2              623   
4             0              0   70               0      2              354   

   Seat comfort  Departure/Arrival time convenient  Food and drink  \
0             0                                  0               0   
1             0                                  0               0   
2             0                                  0               0   
3             0                                  0               0   
4             0                                  0               0   

   Gate location  ...  Online support  Ease of Online booking  \
0              2  ...               2                       3   
1              3  ...               2                       3   
2              3  ...               2                       2   
3              3  ...               3                       1   
4              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [31]:
df.dtypes

satisfaction                           int64
Customer Type                          int64
Age                                    int64
Type of Travel                         int64
Class                                  int64
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
dtype: obj

In [32]:
df.columns.values

array(['satisfaction', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink',
       'Gate location', 'Inflight wifi service', 'Inflight entertainment',
       'Online support', 'Ease of Online booking', 'On-board service',
       'Leg room service', 'Baggage handling', 'Checkin service',
       'Cleanliness', 'Online boarding', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'], dtype=object)

In [33]:
df.corr()

satisfaction  Customer Type       Age  \
satisfaction                           1.000000       0.292592 -0.117971   
Customer Type                          0.292592       1.000000 -0.284172   
Age                                   -0.117971      -0.284172  1.000000   
Type of Travel                        -0.109239       0.308236  0.044808   
Class                                  0.305535       0.105641 -0.140504   
Flight Distance                        0.039224       0.018938 -0.249625   
Seat comfort                          -0.242384      -0.042845  0.008784   
Departure/Arrival time convenient      0.015507      -0.186053  0.039055   
Food and drink                        -0.120677      -0.048725  0.015749   
Gate location                          0.012071      -0.000522 -0.000547   
Inflight wifi service                 -0.227062      -0.073400  0.013965   
Inflight entertainment                -0.523496      -0.235757  0.130511   
Online support                        -0.390143      -0.186154  0.121201   
Ease of Online booking                -0.431772      -0.149664  0.071594   
On-board service                      -0.352047      -0.085433  0.066704   
Leg room service                      -0.304928      -0.097179  0.083762   
Baggage handling                      -0.260347      -0.000639 -0.015452   
Checkin service                       -0.266179      -0.044353  0.031845   
Cleanliness                           -0.259330      -0.002333 -0.018271   
Online boarding                       -0.338147      -0.106394  0.037973   
Departure Delay in Minutes             0.073909       0.003859 -0.009041   
Arrival Delay in Minutes               0.080637       0.004650 -0.011318   

                                   Type of Travel     Class  Flight Distance  \
satisfaction                            -0.109239  0.305535         0.039224   
Customer Type                            0.308236  0.105641         0.018938   
Age                                      0.044808 -0.140504        -0.249625   
Type of Travel                           1.000000 -0.545447         0.122762   
Class                                   -0.545447  1.000000        -0.156763   
Flight Distance                          0.122762 -0.156763         1.000000   
Seat comfort                            -0.016839  0.029539        -0.042409   
Departure/Arrival time convenient       -0.191525  0.054372         0.001350   
Food and drink                           0.031751 -0.049988        -0.004649   
Gate location                            0.013801  0.004061        -0.002409   
Inflight wifi service                    0.019321 -0.061161         0.012230   
Inflight entertainment                   0.079576 -0.241687        -0.027542   
Online support                           0.039385 -0.177992        -0.032022   
Ease of Online booking                   0.025790 -0.128616        -0.022299   
On-board service                        -0.035899 -0.160818        -0.032559   
Leg room service                        -0.013896 -0.125820        -0.030316   
Baggage handling                        -0.048421 -0.120381         0.019768   
Checkin service                         -0.057253 -0.129967         0.002456   
Cleanliness                             -0.058405 -0.114833         0.009432   
Online boarding                          0.009368 -0.097763         0.009604   
Departure Delay in Minutes               0.005913  0.009877         0.112555   
Arrival Delay in Minutes                 0.005577  0.014234         0.110114   

                                   Seat comfort  \
satisfaction                          -0.242384   
Customer Type                         -0.042845   
Age                                    0.008784   
Type of Travel                        -0.016839   
Class                                  0.029539   
Flight Distance                       -0.042409   
Seat comfort                           1.000000   
Departure/Arrival time convenient    

In [34]:
df.drop(['Customer Type', 'Age', 'Type of Travel','Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink',
       'Gate location'] , axis = 1 , inplace = True)

In [35]:
df.head()

satisfaction  Class  Inflight wifi service  Inflight entertainment  \
0             0      2                      2                       4   
1             0      0                      0                       2   
2             0      2                      2                       0   
3             0      2                      3                       4   
4             0      2                      4                       3   

   Online support  Ease of Online booking  On-board service  Leg room service  \
0               2                       3                 3                 0   
1               2                       3                 4                 4   
2               2                       2                 3                 3   
3               3                       1                 1                 0   
4               4                       2                 2                 0   

   Baggage handling  Checkin service  Cleanliness  Online boarding  \
0                 3                5            3                2   
1                 4                2            3                2   
2                 4                4            4                2   
3                 1                4            1                3   
4                 2                4            2                5   

   Departure Delay in Minutes  Arrival Delay in Minutes  
0                           0                       0.0  
1                         310                     305.0  
2                           0                       0.0  
3                           0                       0.0  
4                           0                       0.0

In [36]:
df.corr()

satisfaction     Class  Inflight wifi service  \
satisfaction                    1.000000  0.305535              -0.227062   
Class                           0.305535  1.000000              -0.061161   
Inflight wifi service          -0.227062 -0.061161               1.000000   
Inflight entertainment         -0.523496 -0.241687               0.253823   
Online support                 -0.390143 -0.177992               0.557340   
Ease of Online booking         -0.431772 -0.128616               0.601100   
On-board service               -0.352047 -0.160818               0.060794   
Leg room service               -0.304928 -0.125820               0.033589   
Baggage handling               -0.260347 -0.120381               0.038251   
Checkin service                -0.266179 -0.129967               0.092508   
Cleanliness                    -0.259330 -0.114833               0.038263   
Online boarding                -0.338147 -0.097763               0.631786   
Departure Delay in Minutes      0.073909  0.009877              -0.032900   
Arrival Delay in Minutes        0.080637  0.014234              -0.035197   

                            Inflight entertainment  Online support  \
satisfaction                             -0.523496       -0.390143   
Class                                    -0.241687       -0.177992   
Inflight wifi service                     0.253823        0.557340   
Inflight entertainment                    1.000000        0.441957   
Online support                            0.441957        1.000000   
Ease of Online booking                    0.321731        0.617489   
On-board service                          0.183912        0.157930   
Leg room service                          0.160731        0.138433   
Baggage handling                          0.117213        0.102444   
Checkin service                           0.224120        0.206824   
Cleanliness                               0.109451        0.095726   
Online boarding                           0.355714        0.669843   
Departure Delay in Minutes               -0.030491       -0.034018   
Arrival Delay in Minutes                 -0.033389       -0.036150   

                            Ease of Online booking  On-board service  \
satisfaction                             -0.431772         -0.352047   
Class                                    -0.128616         -0.160818   
Inflight wifi service                     0.601100          0.060794   
Inflight entertainment                    0.321731          0.183912   
Online support                            0.617489          0.157930   
Ease of Online booking                    1.000000          0.436264   
On-board service                          0.436264          1.000000   
Leg room service                          0.355122          0.411746   
Baggage handling                          0.398322          0.530448   
Checkin service                           0.137744          0.250839   
Cleanliness                               0.417675          0.551294   
Online boarding                           0.684320          0.139506   
Departure Delay in Minutes               -0.036545         -0.037641   
Arrival Delay in Minutes                 -0.039738         -0.041419   

                            Leg room service  Baggage handling  \
satisfaction                       -0.304928         -0.260347   
Class                              -0.125820         -0.120381   
Inflight wifi service               0.033589          0.038251   
Inflight entertainment              0.160731          0.117213   
Online support                      0.138433          0.102444   
Ease of Online booking              0.355122          0.398322   
On-board service                    0.411746          0.530448   
Leg room service                    1.000000          0.411640   
Baggage handling                    0.411640          1.000000   
Checkin service                     0.167942          0.240858   
Cleanliness   

In [37]:
df.drop(['Inflight wifi service','Leg room service','Baggage handling','Departure Delay in Minutes',
       'Arrival Delay in Minutes'], axis = 1 , inplace = True)

In [38]:
df.head()

satisfaction  Class  Inflight entertainment  Online support  \
0             0      2                       4               2   
1             0      0                       2               2   
2             0      2                       0               2   
3             0      2                       4               3   
4             0      2                       3               4   

   Ease of Online booking  On-board service  Checkin service  Cleanliness  \
0                       3                 3                5            3   
1                       3                 4                2            3   
2                       2                 3                4            4   
3                       1                 1                4            1   
4                       2                 2                4            2   

   Online boarding  
0                2  
1                2  
2                2  
3                3  
4                5

In [39]:
x = df.drop('satisfaction' , axis = 1)

In [40]:
x.head()

Class  Inflight entertainment  Online support  Ease of Online booking  \
0      2                       4               2                       3   
1      0                       2               2                       3   
2      2                       0               2                       2   
3      2                       4               3                       1   
4      2                       3               4                       2   

   On-board service  Checkin service  Cleanliness  Online boarding  
0                 3                5            3                2  
1                 4                2            3                2  
2                 3                4            4                2  
3                 1                4            1                3  
4                 2                4            2                5

In [41]:
y = df['satisfaction']
y

0         0
1         0
2         0
3         0
4         0
         ..
129875    0
129876    1
129877    1
129878    1
129879    1
Name: satisfaction, Length: 129880, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train , x_test , y_train , y_test = train_test_split(x , y, test_size = 0.30 ,random_state = 42)

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
model = LogisticRegression(max_iter = 500)

In [46]:
model.fit(x_train , y_train)

LogisticRegression(max_iter=500)

In [47]:
y_pred = model.predict(x_test)

In [48]:
y_pred

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [49]:
y_test

103044    0
43282     1
65543     0
65083     0
76496     1
         ..
32347     1
123061    0
74700     1
54997     1
107396    0
Name: satisfaction, Length: 38964, dtype: int64

In [50]:
from sklearn.metrics import accuracy_score,classification_report

In [51]:
print(accuracy_score(y_test,y_pred))

0.80510214557027


In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82     21410
           1       0.79      0.78      0.78     17554

    accuracy                           0.81     38964
   macro avg       0.80      0.80      0.80     38964
weighted avg       0.81      0.81      0.81     38964



In [53]:
x_test.iloc[0]

Class                     0
Inflight entertainment    4
Online support            4
Ease of Online booking    4
On-board service          4
Checkin service           5
Cleanliness               4
Online boarding           3
Name: 103044, dtype: int64

In [54]:
prediction = [1,5,4,5,3,4,5,1]

In [55]:
model.predict([prediction])

C:\Users\KARTHIKA\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)